import "server-only";
import { getD1 } from "@/lib/d1/runtime";
import type { D1Service } from "@/lib/d1/types";
import type { PCMPackageListItem, PCMListResponse, PCMServiceListItem } from "@/types/pcm";
import { allWithMetrics } from "@/lib/d1/metrics";

export function normStatus(value?:string|null) { const s=(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase(); return s.includes("concl")||s==="encerrado"?"Concluído":s.includes("pend")?"Pendente":"Aberto"; }
const dbStatus=(value?:string|null)=>normStatus(value)==="Concluído"?"concluded":normStatus(value)==="Pendente"?"pending":"open";
const encode=(updated_at:number,id:string)=>Buffer.from(JSON.stringify({updated_at,id})).toString("base64url");
const decode=(cursor?:string|null):{updated_at:number;id:string}|null=>{ try { const v=JSON.parse(Buffer.from(cursor??"","base64url").toString()); return Number.isFinite(v.updated_at)&&typeof v.id==="string"?v:null; } catch{return null;} };
const map=(r:D1Service):PCMServiceListItem=>({id:r.id,os:r.os,oc:r.oc,code:r.code,tag:r.tag,equipmentName:r.equipment_name,equipamento:r.equipment_name,sector:r.sector,setor:r.sector,status:normStatus(r.status),andamento:r.progress,progress:r.progress,realPercent:r.progress,packageId:r.package_id,empresa:r.company_name??r.company_id,company:r.company_name??r.company_id,cnpj:r.cnpj,createdAt:r.created_at,updatedAt:r.updated_at,plannedStart:r.planned_start,plannedEnd:r.planned_end,plannedDaily:r.planned_daily_json?JSON.parse(r.planned_daily_json):null,assignedTo:r.company_id?{companyId:r.company_id,companyName:r.company_name}:null});
const serviceFields="s.id,s.os,s.oc,s.code,s.tag,s.equipment_name,s.sector,s.planned_start,s.planned_end,s.total_hours,s.description,s.status,s.progress,s.company_id,s.company_name,s.cnpj,s.package_id,s.previous_progress,0 AS has_checklist,'[]' AS checklist_json,NULL AS planned_daily_json,s.import_key,s.created_at,s.updated_at";

export async function listServicesPCM(options?:{limit?:number;cursor?:string|null;status?:string|null;empresa?:string|null;search?:string|null}):Promise<PCMListResponse<PCMServiceListItem>> {
  const limit=Math.min(Math.max(Math.floor(options?.limit??10),1),100), values:unknown[]=[]; const clauses:string[]=[]; const cursor=decode(options?.cursor);
  if(options?.status){values.push(dbStatus(options.status));clauses.push(`s.status=?${values.length}`);} if(options?.empresa){values.push(options.empresa);clauses.push(`s.company_id=?${values.length}`);}
  let from="services s"; if(options?.search?.trim()){from="services_fts f JOIN services s ON s.rowid=f.rowid";values.push(`"${options.search.trim().replaceAll('"','""')}"`);clauses.push(`f.services_fts MATCH ?${values.length}`);}
  if(cursor){values.push(cursor.updated_at,cursor.id);clauses.push(`(s.updated_at < ?${values.length-1} OR (s.updated_at=?${values.length-1} AND s.id<?${values.length}))`);}
  values.push(limit+1); const rows=await allWithMetrics<D1Service>(options?.search?.trim()?"services.search":"services.page",getD1().prepare(`SELECT ${serviceFields} FROM ${from} ${clauses.length?`WHERE ${clauses.join(" AND ")}`:""} ORDER BY s.updated_at DESC,s.id DESC LIMIT ?${values.length}`).bind(...values));
  const items=rows.slice(0,limit).map(map), last=rows.length>limit?rows[limit-1]:null; return {items,nextCursor:last?encode(last.updated_at,last.id):null};
}
export async function listPackagesPCM(options?:{limit?:number;cursor?:string|null}):Promise<PCMListResponse<PCMPackageListItem>> { const limit=Math.min(Math.max(options?.limit??10,1),100), c=decode(options?.cursor); const q=c?getD1().prepare("SELECT id,name,status,code,created_at,services_count FROM packages WHERE created_at<?1 OR(created_at=?1 AND id<?2) ORDER BY created_at DESC,id DESC LIMIT ?3").bind(c.updated_at,c.id,limit+1):getD1().prepare("SELECT id,name,status,code,created_at,services_count FROM packages ORDER BY created_at DESC,id DESC LIMIT ?1").bind(limit+1); const rows=(await q.all<Record<string,unknown>>()).results??[]; const items=rows.slice(0,limit).map(r=>({id:String(r.id),name:String(r.name),status:normStatus(String(r.status)),code:r.code?String(r.code):null,createdAt:Number(r.created_at),servicesCount:Number(r.services_count)}));const last=rows.length>limit?rows[limit-1]:null;return{items,nextCursor:last?encode(Number(last.created_at),String(last.id)):null}; }
export async function listServicesForToken(tokenDoc:unknown,options?:{limit?:number}) { if(!tokenDoc||typeof tokenDoc!=="object")return[];const t=tokenDoc as Record<string,unknown>;const id=String(t.serviceId??t.targetId??"");if(id){const r=await getD1().prepare(`SELECT ${serviceFields} FROM services s WHERE s.id=?1 AND s.status IN('open','pending')`).bind(id).first<D1Service>();return r?[map(r)]:[];}const packageId=String(t.packageId??"");const company=String(t.empresa??t.companyId??"");if(!packageId)return[];const rows=(await getD1().prepare(`SELECT ${serviceFields} FROM services s WHERE s.package_id=?1 AND (?2='' OR s.company_id=?2) AND s.status IN('open','pending') LIMIT ?3`).bind(packageId,company,Math.min(options?.limit??50,200)).all<D1Service>()).results??[];return rows.map(map); }
