import "server-only";
import { revalidatePath,revalidateTag } from "next/cache";
import { getD1 } from "@/lib/d1/runtime";
import { buildChecklistWeightMap,clampPercent,computeProgressFromEvents,type ProgressEvent } from "./progressHistory";
type Row={created_at:number;report_date:number|null;manual_percent:number|null;real_percent:number|null;payload_json:string};
export async function loadProgressHistory(_unused:unknown,serviceId:string){const service=await getD1().prepare("SELECT checklist_json,package_id FROM services WHERE id=?1").bind(serviceId).first<{checklist_json:string;package_id:string|null}>();const rows=(await getD1().prepare("SELECT created_at,report_date,manual_percent,real_percent,payload_json FROM service_updates WHERE service_id=?1 ORDER BY created_at ASC,id ASC").bind(serviceId).all<Row>()).results??[];const checklist=service?JSON.parse(service.checklist_json):[],{weights,totalWeight}=buildChecklistWeightMap(checklist);let lastManualUpdate:{percent:number;timestamp:number}|null=null;const events:ProgressEvent[]=rows.map(r=>{const p=JSON.parse(r.payload_json) as {items?:Array<{id:string;pct:number}>};const timestamp=r.report_date??r.created_at,percent=r.manual_percent??r.real_percent;if(r.manual_percent!==null)lastManualUpdate={percent:clampPercent(r.manual_percent),timestamp};return{timestamp,percent:percent===null?null:clampPercent(percent),items:p.items,explicitDate:r.report_date!==null};});return{events,lastManualUpdate,weights,totalWeight,serviceData:{packageId:service?.package_id}};}
async function history(id:string){return loadProgressHistory(null,id);}
export async function recomputeServiceProgress(id:string){const {events,lastManualUpdate,weights,totalWeight}=await history(id),computed=computeProgressFromEvents(events,{weights,totalWeight});const manual=lastManualUpdate as {percent:number;timestamp:number}|null;const percent=manual&&(computed.lastTimestamp===null||manual.timestamp>=computed.lastTimestamp)?manual.percent:computed.currentPercent;const updated=computed.lastTimestamp??Date.now();await getD1().prepare("UPDATE services SET progress=?1,status=CASE WHEN ?1>=100 THEN 'concluded' ELSE status END,updated_at=?2 WHERE id=?3").bind(percent,updated,id).run();["services:detail","services:updates","services:available","services:recent","packages:detail","packages:summary","packages:services"].forEach(revalidateTag);revalidatePath(`/servicos/${id}`);return{percent,lastUpdate:computed.lastTimestamp};}
export async function computeProgressHistory(id:string){const {events,weights,totalWeight}=await history(id);return computeProgressFromEvents(events,{weights,totalWeight});}
