import "server-only";
import { getD1 } from "@/lib/d1/runtime";
import { mapFolder,mapService } from "@/lib/d1/mapper";
import type { D1Service } from "@/lib/d1/types";
import type { ChecklistItem,Service } from "@/lib/types";
export class PublicAccessError extends Error{constructor(public status:number,message:string){super(message)}}
type Token={token_code:string;target_type:string;target_id:string;company_id:string|null;package_id:string|null;active:number;status:string|null;expires_at:number|null;one_time:number;created_at:number;updated_at:number;targetType?:string;targetId?:string;companyId?:string;packageId?:string};
const sf="id,os,oc,code,tag,equipment_name,sector,planned_start,planned_end,total_hours,description,status,progress,company_id,company_name,cnpj,package_id,previous_progress,has_checklist,checklist_json,planned_daily_json,import_key,created_at,updated_at";
async function token(code:string){const r=await getD1().prepare("SELECT token_code,target_type,target_id,company_id,package_id,active,status,expires_at,one_time,created_at,updated_at FROM access_tokens WHERE token_code=?1 LIMIT 1").bind(code.trim().toUpperCase()).first<Token>();if(!r)throw new PublicAccessError(404,"Token inválido");if(!r.active||r.status==="revoked")throw new PublicAccessError(403,"Token inativo");if(r.expires_at&&r.expires_at<Date.now())throw new PublicAccessError(403,"Token expirado");return Object.assign(r,{targetType:r.target_type,targetId:r.target_id,companyId:r.company_id??undefined,packageId:r.package_id??undefined});}
const matchCompany=(t:Token,s:Service)=>{if(!t.company_id)return;const digits=(x:string)=>x.replace(/\D/g,"");const values=[s.company,s.empresa,s.cnpj,s.assignedTo?.companyId].filter((x):x is string=>Boolean(x));if(!values.includes(t.company_id)&&!values.some(x=>digits(x)&&digits(x)===digits(t.company_id!)))throw new PublicAccessError(403,"Token não possui acesso a este serviço");};
export async function requireFolderAccess(code:string,folderId:string){const t=await token(code);if(t.target_type!=="folder"||t.target_id!==folderId)throw new PublicAccessError(403,"Token não possui acesso a este subpacote");const row=await getD1().prepare("SELECT id,package_id,name,company_id,service_ids_json,token_code,created_at,updated_at,token_created_at FROM package_folders WHERE id=?1").bind(folderId).first<Record<string,unknown>>();if(!row)throw new PublicAccessError(404,"Subpacote não encontrado");const folder=mapFolder(row);if(t.company_id&&folder.companyId&&t.company_id!==folder.companyId)throw new PublicAccessError(403,"Token não possui acesso a esta pasta");if(t.package_id&&t.package_id!==folder.packageId)throw new PublicAccessError(403,"Token não corresponde ao pacote do subpacote");const ids=folder.services;let services:Service[]=[];if(ids.length)services=((await getD1().prepare(`SELECT ${sf} FROM services WHERE id IN(${ids.map((_:string,i:number)=>`?${i+1}`).join(",")})`).bind(...ids).all<D1Service>()).results??[]).map(mapService);const found=new Set(services.map(s=>s.id));return{token:t,folder:{id:folder.id,name:folder.name,company:folder.companyId??null,packageId:folder.packageId,services:ids},services,unavailableServices:ids.filter((id:string)=>!found.has(id))};}
export async function requireServiceAccess(code:string,id:string,preloaded?:Token){const t=preloaded??await token(code);let folderId:string|undefined;if(t.target_type==="service"){if(t.target_id!==id)throw new PublicAccessError(403,"Token não corresponde ao serviço");}else if(t.target_type==="folder"){const access=await requireFolderAccess(code,t.target_id);if(!access.folder.services.includes(id))throw new PublicAccessError(403,"Serviço não faz parte desta pasta");folderId=t.target_id;}else throw new PublicAccessError(403,"Token não corresponde ao serviço");const row=await getD1().prepare(`SELECT ${sf} FROM services WHERE id=?1`).bind(id).first<D1Service>();if(!row)throw new PublicAccessError(404,"Serviço não encontrado");const service=mapService(row);if(!folderId)matchCompany(t,service);return{token:t,service,folderId};}
export async function fetchServiceChecklist(id:string):Promise<ChecklistItem[]>{const r=await getD1().prepare("SELECT checklist_json FROM services WHERE id=?1").bind(id).first<{checklist_json:string}>();return r?JSON.parse(r.checklist_json):[];}
export async function resolvePublicAccessRedirect(code:string){const t=await token(code);if(t.target_type==="service"){await requireServiceAccess(code,t.target_id,t);return{redirectPath:`/s/${t.target_id}`,targetType:"service" as const,targetId:t.target_id};}if(t.target_type==="folder"){await requireFolderAccess(code,t.target_id);return{redirectPath:`/subpacotes/${t.target_id}`,targetType:"folder" as const,targetId:t.target_id};}throw new PublicAccessError(400,"Token sem destino configurado");}
