import "server-only";
import { getD1 } from "@/lib/d1/runtime";
import { mapService } from "@/lib/d1/mapper";
import type { D1Service } from "@/lib/d1/types";
export type TokenDoc={id:string}&Record<string,unknown>;
type Row={token_code:string;target_type:string;target_id:string;company_id:string|null;package_id:string|null;active:number;status:string|null;expires_at:number|null;one_time:number;created_at:number;updated_at:number};
const sf="id,os,oc,code,tag,equipment_name,sector,planned_start,planned_end,total_hours,description,status,progress,company_id,company_name,cnpj,package_id,previous_progress,has_checklist,checklist_json,planned_daily_json,import_key,created_at,updated_at";
export async function getTokenDoc(value:string){const r=await getD1().prepare("SELECT token_code,target_type,target_id,company_id,package_id,active,status,expires_at,one_time,created_at,updated_at FROM access_tokens WHERE token_code=?1").bind(value.trim().toUpperCase()).first<Row>();return r?{id:r.token_code,code:r.token_code,targetType:r.target_type,targetId:r.target_id,serviceId:r.target_type==="service"?r.target_id:undefined,folderId:r.target_type==="folder"?r.target_id:undefined,company:r.company_id,packageId:r.package_id,active:Boolean(r.active),status:r.status,expiresAt:r.expires_at}:null;}
export async function getServicesForToken(value:string){const t=await getTokenDoc(value);if(!t||!t.active||t.status==="revoked"||typeof t.expiresAt==="number"&&t.expiresAt<Date.now())return[];let ids:string[]=[];if(t.targetType==="service")ids=[String(t.targetId)];else{const f=await getD1().prepare("SELECT service_ids_json FROM package_folders WHERE id=?1").bind(String(t.targetId)).first<{service_ids_json:string}>();ids=f?JSON.parse(f.service_ids_json):[];}if(!ids.length)return[];return ((await getD1().prepare(`SELECT ${sf} FROM services WHERE id IN(${ids.map((_,i)=>`?${i+1}`).join(",")})`).bind(...ids).all<D1Service>()).results??[]).map(mapService).map(s=>({id:s.id,os:s.os,oc:s.oc,tag:s.tag,equipamento:s.equipmentName,setor:s.sector,status:String(s.status),andamento:s.progress,packageId:s.packageId??null,empresa:s.company??null,cnpj:s.cnpj??null,description:s.description??null}));}
