"use server";
import { randomUUID } from "crypto";
import { revalidateTag } from "next/cache";
import { randomToken } from "@/lib/accessTokens";
import { getD1 } from "@/lib/d1/runtime";
import { mapFolder } from "@/lib/d1/mapper";
import type { PackageFolder } from "@/types";
const invalidate=()=>["folders:by-package","folders:detail","packages:detail","packages:services","services:available"].forEach(revalidateTag);
const select="SELECT id,package_id,name,company_id,service_ids_json,token_code,created_at,updated_at,token_created_at FROM package_folders";
export async function listPackageFolders(id:string){return ((await getD1().prepare(`${select} WHERE package_id=?1 ORDER BY name COLLATE NOCASE,id`).bind(id).all<Record<string,unknown>>()).results??[]).map(mapFolder);}
export async function getPackageFolder(id:string){const r=await getD1().prepare(`${select} WHERE id=?1`).bind(id).first<Record<string,unknown>>();return r?mapFolder(r):null;}
async function token(folderId:string,packageId:string,companyId?:string|null){for(let i=0;i<6;i++){const code=randomToken(8+i);try{const now=Date.now();await getD1().prepare("INSERT INTO access_tokens(token_code,target_type,target_id,company_id,package_id,active,status,created_at,updated_at) VALUES(?1,'folder',?2,?3,?4,1,'active',?5,?5)").bind(code,folderId,companyId??null,packageId,now).run();return code;}catch{continue}}throw new Error("Não foi possível gerar token único para a pasta.");}
export async function createPackageFolder({packageId,name,companyId}:{packageId:string;name:string;companyId?:string|null}){if(!name.trim())throw new Error("Nome da pasta é obrigatório.");const id=randomUUID(),now=Date.now(),code=await token(id,packageId,companyId);await getD1().prepare("INSERT INTO package_folders(id,package_id,name,company_id,service_ids_json,token_code,created_at,updated_at,token_created_at) VALUES(?1,?2,?3,?4,'[]',?5,?6,?6,?6)").bind(id,packageId,name.trim(),companyId?.trim()||null,code,now).run();invalidate();return (await getPackageFolder(id))!;}
export async function updatePackageFolder(id:string,data:{name?:string;companyId?:string|null}){const old=await getPackageFolder(id);if(!old)throw new Error("Pasta não encontrada.");if(data.name!==undefined&&!data.name.trim())throw new Error("Nome da pasta não pode ficar vazio.");await getD1().prepare("UPDATE package_folders SET name=?1,company_id=?2,updated_at=?3 WHERE id=?4").bind(data.name?.trim()||old.name,data.companyId===undefined?old.companyId:data.companyId?.trim()||null,Date.now(),id).run();invalidate();return (await getPackageFolder(id))!;}
export async function setFolderServices(id:string,serviceIds:string[]):Promise<PackageFolder>{const folder=await getPackageFolder(id);if(!folder)throw new Error("Pasta não encontrada.");const unique=[...new Set(serviceIds.map((x:string)=>x.trim()).filter(Boolean))];if(unique.length){const rows=(await getD1().prepare(`SELECT id,package_id FROM services WHERE id IN(${unique.map((_:string,i:number)=>`?${i+1}`).join(",")})`).bind(...unique).all<{id:string;package_id:string|null}>()).results??[];if(rows.some(r=>r.package_id&&r.package_id!==folder.packageId))throw new Error("Não é permitido vincular um serviço que já pertence a outro pacote.");}const now=Date.now(),previous=folder.services,removed=previous.filter(x=>!unique.includes(x));const batch=[getD1().prepare("UPDATE package_folders SET service_ids_json=?1,updated_at=?2 WHERE id=?3").bind(JSON.stringify(unique),now,id)];if(unique.length)batch.push(getD1().prepare(`UPDATE services SET package_id=?1,updated_at=?2 WHERE id IN(${unique.map((_:string,i:number)=>`?${i+3}`).join(",")})`).bind(folder.packageId,now,...unique));if(removed.length)batch.push(getD1().prepare(`UPDATE services SET package_id=NULL,updated_at=?1 WHERE package_id=?2 AND id IN(${removed.map((_:string,i:number)=>`?${i+3}`).join(",")}) AND NOT EXISTS(SELECT 1 FROM package_folders f WHERE f.id<>?${removed.length+3} AND EXISTS(SELECT 1 FROM json_each(f.service_ids_json) WHERE value=services.id))`).bind(now,folder.packageId,...removed,id));await getD1().batch(batch);invalidate();return (await getPackageFolder(id))!;}
export async function rotateFolderToken(id:string){const f=await getPackageFolder(id);if(!f)throw new Error("Pasta não encontrada.");const code=await token(id,f.packageId,f.companyId);const now=Date.now();await getD1().batch([getD1().prepare("UPDATE access_tokens SET active=0,status='revoked',updated_at=?1 WHERE token_code=?2").bind(now,f.tokenCode),getD1().prepare("UPDATE package_folders SET token_code=?1,token_created_at=?2,updated_at=?2 WHERE id=?3").bind(code,now,id)]);invalidate();return (await getPackageFolder(id))!;}
export async function deletePackageFolder(id:string){const f=await getPackageFolder(id);if(!f)throw new Error("Pasta não encontrada.");const now=Date.now();await getD1().batch([getD1().prepare("UPDATE access_tokens SET active=0,status='revoked',updated_at=?1 WHERE target_type='folder' AND target_id=?2").bind(now,id),getD1().prepare("DELETE FROM package_folders WHERE id=?1").bind(id)]);invalidate();return{deletedId:id,unlinkedServices:f.services.length};}
