"use server";
import { randomUUID } from "crypto";
import { revalidateTag } from "next/cache";
import { getD1 } from "@/lib/d1/runtime";
import { mapPackage,mapService } from "@/lib/d1/mapper";
import type { D1Service } from "@/lib/d1/types";
import type { Package,Service } from "@/lib/types";
import { allWithMetrics } from "@/lib/d1/metrics";
const sf="id,os,oc,code,tag,equipment_name,sector,planned_start,planned_end,total_hours,description,status,progress,company_id,company_name,cnpj,package_id,previous_progress,has_checklist,checklist_json,planned_daily_json,import_key,created_at,updated_at";
const invalidate=()=>["packages:recent","packages:detail","packages:summary","packages:services","services:recent","services:available"].forEach(revalidateTag);
const dbStatus=(s:Package["status"])=>String(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().includes("concl")?"concluded":String(s).toLowerCase().includes("pend")?"pending":"open";
export type PackageSummary=Pick<Package,"id"|"name"|"status"|"code"|"createdAt">&{servicesCount?:number};
export async function getPackage(id:string){const r=await getD1().prepare("SELECT id,name,status,code,description,planned_start,planned_end,total_hours,assigned_companies_json,created_at FROM packages WHERE id=?1").bind(id.trim()).first<Record<string,unknown>>();return r?mapPackage(r):null;}
export const getPackageById=getPackage;export const getPackageByIdCached=getPackage;
export async function listRecentPackages():Promise<PackageSummary[]>{return (await allWithMetrics<Record<string,unknown>>("packages.listRecent",getD1().prepare("SELECT id,name,status,code,description,planned_start,planned_end,total_hours,assigned_companies_json,created_at,services_count FROM packages ORDER BY created_at DESC,id DESC LIMIT 20"))).map(r=>({...mapPackage(r),servicesCount:Number(r.services_count)}));}
export async function listPackageServices(id:string,options?:{limit?:number}):Promise<Service[]>{return (await allWithMetrics<D1Service>("packages.listServices",getD1().prepare(`SELECT ${sf} FROM services WHERE package_id=?1 ORDER BY created_at DESC,id DESC LIMIT ?2`).bind(id,Math.min(options?.limit??100,2000)))).map(mapService);}
export async function createPackage(name:string,serviceIds:string[]){const id=randomUUID(),now=Date.now(),unique=[...new Set(serviceIds.map(x=>x.trim()).filter(Boolean))];const statements=[getD1().prepare("INSERT INTO packages(id,name,status,created_at,updated_at) VALUES(?1,?2,'open',?3,?3)").bind(id,name.trim(),now)];if(unique.length)statements.push(getD1().prepare(`UPDATE services SET package_id=?1,updated_at=?2 WHERE id IN(${unique.map((_,i)=>`?${i+3}`).join(",")})`).bind(id,now,...unique));await getD1().batch(statements);invalidate();return id;}
export async function updatePackageMetadata(id:string,data:{name?:string;description?:string|null;plannedStart?:string;plannedEnd?:string;status?:Package["status"];code?:string|null}){const old=await getPackage(id);if(!old)throw new Error("Pacote não encontrado.");const start=data.plannedStart!==undefined?Date.parse(`${data.plannedStart}T00:00:00Z`):Date.parse(old.plannedStart),end=data.plannedEnd!==undefined?Date.parse(`${data.plannedEnd}T00:00:00Z`):Date.parse(old.plannedEnd);if(Number.isFinite(start)&&Number.isFinite(end)&&start>end)throw new Error("A data final deve ser posterior ou igual à data inicial.");await getD1().prepare("UPDATE packages SET name=?1,description=?2,planned_start=?3,planned_end=?4,status=?5,code=?6,updated_at=?7 WHERE id=?8").bind(data.name?.trim()||old.name,data.description===undefined?old.description:data.description?.trim()||null,Number.isFinite(start)?start:null,Number.isFinite(end)?end:null,data.status?dbStatus(data.status):dbStatus(old.status),data.code===undefined?old.code:data.code?.trim()||null,Date.now(),id).run();invalidate();return (await getPackage(id))!;}
export async function deletePackage(id:string){if(!await getPackage(id))return false;const now=Date.now();await getD1().batch([getD1().prepare("UPDATE services SET package_id=NULL,updated_at=?1 WHERE package_id=?2").bind(now,id),getD1().prepare("UPDATE access_tokens SET active=0,status='revoked',updated_at=?1 WHERE package_id=?2 OR(target_type='folder' AND target_id IN(SELECT id FROM package_folders WHERE package_id=?2))").bind(now,id),getD1().prepare("DELETE FROM packages WHERE id=?1").bind(id)]);invalidate();return true;}
