"use server";
import { randomUUID } from "crypto";
import { revalidateTag } from "next/cache";
import { getD1 } from "@/lib/d1/runtime";
import { mapService, mapUpdate } from "@/lib/d1/mapper";
import type { D1Service,D1Update } from "@/lib/d1/types";
import type { ChecklistItem,Service,ServiceStatus,ServiceUpdate } from "@/lib/types";
import { allWithMetrics, firstWithMetrics } from "@/lib/d1/metrics";

type ChecklistSeed={id:string;descricao:string; peso:number};
type CreateServicePayload={os:string;oc:string|null;tag:string;equipamento:string;equipmentName?:string|null;setor:string|null;inicioPrevistoMillis:number;fimPrevistoMillis:number;horasPrevistas:number;empresaId:string|null;cnpj:string|null;status:ServiceStatus;checklist:ChecklistSeed[];description?:string|null;importKey?:string|null};
type ServiceMetadataInput={os:string;tag:string;equipment:string;oc?:string|null;sector?:string|null;company?:string|null;cnpj?:string|null;plannedStart:string;plannedEnd:string;totalHours:number;status:ServiceStatus};
type ManualUpdateInput={manualPercent:number;description:string;token?:string;mode:"simple"|"detailed";declarationAccepted:boolean;reportDate?:number|null;timeWindow?:ServiceUpdate["timeWindow"];subactivity?:ServiceUpdate["subactivity"];impediments?:ServiceUpdate["impediments"];resources?:ServiceUpdate["resources"];workforce?:ServiceUpdate["workforce"];shiftConditions?:ServiceUpdate["shiftConditions"];forecastDate?:number|null;criticality?:number|null;evidences?:ServiceUpdate["evidences"];justification?:string|null;previousPercent?:number|null;ip?:string|null};
const fields="id,os,oc,code,tag,equipment_name,sector,planned_start,planned_end,total_hours,description,status,progress,company_id,company_name,cnpj,package_id,previous_progress,has_checklist,checklist_json,planned_daily_json,import_key,created_at,updated_at";
const summaryFields="id,os,oc,code,tag,equipment_name,sector,planned_start,planned_end,total_hours,description,status,progress,company_id,company_name,cnpj,package_id,previous_progress,0 AS has_checklist,'[]' AS checklist_json,NULL AS planned_daily_json,import_key,created_at,updated_at";
const status=(s:ServiceStatus)=>String(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().includes("concl")?"concluded":String(s).toLowerCase().includes("pend")?"pending":"open";
const clamp=(n:number)=>Math.max(0,Math.min(100,Number.isFinite(n)?n:0));
const tags=()=>["services:recent","services:detail","services:available","services:checklist","services:updates"].forEach(t=>revalidateTag(t));
const placeholders=(n:number)=>Array.from({length:n},(_,i)=>`?${i+1}`).join(",");
export async function buildServiceImportKey(input:Record<string,unknown>){return Object.values(input).map(v=>String(v??"").trim().toLowerCase()).filter(Boolean).join("::");}
export async function createService(p:CreateServicePayload){const id=randomUUID(),now=Date.now();const checklist:ChecklistItem[]=p.checklist.map(i=>({id:i.id||randomUUID(),description:i.descricao,weight:i.peso,progress:0,status:"nao-iniciado"}));await getD1().prepare("INSERT INTO services(id,os,oc,tag,equipment_name,sector,planned_start,planned_end,total_hours,description,status,progress,company_id,company_name,cnpj,has_checklist,checklist_json,import_key,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,0,?12,?12,?13,?14,?15,?16,?17,?17)").bind(id,p.os,p.oc,p.tag,p.equipmentName??p.equipamento,p.setor,p.inicioPrevistoMillis,p.fimPrevistoMillis,p.horasPrevistas,p.description??null,status(p.status),p.empresaId,p.cnpj,checklist.length?1:0,JSON.stringify(checklist),p.importKey??null,now).run();tags();return {id};}
export async function getServiceById(id:string){const row=await firstWithMetrics<D1Service>("services.get",getD1().prepare(`SELECT ${fields} FROM services WHERE id=?1 LIMIT 1`).bind(id.trim()));return row?mapService(row):null;}
export const getService=getServiceById;
export async function getServicesByIds(ids:string[],_options?:{mode?:"summary"|"full"}):Promise<Service[]>{const unique=[...new Set(ids.map(x=>x.trim()).filter(Boolean))];if(!unique.length)return[];const rows=(await getD1().prepare(`SELECT ${fields} FROM services WHERE id IN(${placeholders(unique.length)})`).bind(...unique).all<D1Service>()).results??[];const by=new Map(rows.map(r=>[r.id,mapService(r)]));return unique.flatMap(id=>by.has(id)?[by.get(id)!]:[]);}
export async function findServicesByImportKeys(keys:string[]){return byValues("import_key",keys);}
export async function findServicesByOsList(keys:string[]){return byValues("os",keys);}
async function byValues(column:"import_key"|"os",values:string[]){const v=[...new Set(values.filter(Boolean))];if(!v.length)return[];return ((await getD1().prepare(`SELECT ${fields} FROM services WHERE ${column} IN(${placeholders(v.length)})`).bind(...v).all<D1Service>()).results??[]).map(mapService);}
export async function listRecentServices(){return (await allWithMetrics<D1Service>("services.listRecent",getD1().prepare(`SELECT ${summaryFields} FROM services ORDER BY updated_at DESC,id DESC LIMIT 20`))).map(mapService);}
export type ServiceStatusSummary={total:number;open:number;pending:number;concluded:number};
export async function getServiceStatusSummary(){return firstWithMetrics<ServiceStatusSummary>("stats.get",getD1().prepare("SELECT total,open,pending,concluded FROM service_stats WHERE id=1 LIMIT 1"));}
export async function listAvailableOpenServices(options?:number|{limit?:number;mode?:unknown},_mode?:unknown){const limit=typeof options==="number"?options:options?.limit??200;return (await allWithMetrics<D1Service>("services.listAvailable",getD1().prepare(`SELECT ${summaryFields} FROM services INDEXED BY idx_services_available WHERE package_id IS NULL AND status IN('open','pending') AND progress<100 ORDER BY created_at DESC,id DESC LIMIT ?1`).bind(Math.min(Math.max(limit,1),500)))).map(mapService);}
export async function getChecklist(id:string){return (await getServiceById(id))?.checklist??[];}
export async function setChecklistItems(id:string,items:Array<{description:string;weight:number}>){if(items.length&&Math.round(items.reduce((a,x)=>a+x.weight,0))!==100)throw new Error("A soma dos pesos do checklist deve ser igual a 100.");const list=items.map(x=>({id:randomUUID(),description:x.description,weight:x.weight,progress:0,status:"nao-iniciado"}));await getD1().prepare("UPDATE services SET checklist_json=?1,has_checklist=?2,progress=0,status='open',updated_at=?3 WHERE id=?4").bind(JSON.stringify(list),list.length?1:0,Date.now(),id).run();tags();}
export async function updateServiceMetadata(id:string,input:ServiceMetadataInput){const existing=await getServiceById(id);if(!existing)throw new Error("Serviço não encontrado");const newStatus=status(input.status), concluding=newStatus==="concluded", reopening=existing.status==="Concluído"&&newStatus!=="concluded";const progress=concluding?100:reopening?(existing.previousProgress??0):(existing.progress??0);await getD1().prepare("UPDATE services SET os=?1,oc=?2,tag=?3,equipment_name=?4,sector=?5,company_id=?6,company_name=?6,cnpj=?7,planned_start=?8,planned_end=?9,total_hours=?10,status=?11,progress=?12,previous_progress=CASE WHEN ?11='concluded' THEN progress ELSE previous_progress END,updated_at=?13 WHERE id=?14").bind(input.os,input.oc??null,input.tag,input.equipment,input.sector??null,input.company??null,input.cnpj??null,Date.parse(input.plannedStart),Date.parse(input.plannedEnd),input.totalHours,newStatus,progress,Date.now(),id).run();tags();}
export async function updateChecklistProgress(id:string,updates:Array<{id:string;progress:number;status?:ChecklistItem["status"]}>){const service=await getServiceById(id);if(!service)throw Object.assign(new Error("Serviço não encontrado"),{status:404});const map=new Map(updates.map(u=>[u.id,u]));const checklist=(service.checklist??[]).map(i=>{const u=map.get(i.id);const progress=u?clamp(u.progress):i.progress;return{...i,progress,status:u?.status??(progress>=100?"concluido":progress>0?"em-andamento":"nao-iniciado")};});for(const u of updates)if(!checklist.some(i=>i.id===u.id))throw Object.assign(new Error(`Item do checklist ${u.id} não encontrado`),{status:404});const weight=checklist.reduce((a,i)=>a+i.weight,0),progress=weight?checklist.reduce((a,i)=>a+i.progress*i.weight,0)/weight:0;await getD1().prepare("UPDATE services SET checklist_json=?1,has_checklist=1,progress=?2,status=CASE WHEN ?2>=100 THEN 'concluded' ELSE status END,updated_at=?3 WHERE id=?4").bind(JSON.stringify(checklist),clamp(progress),Date.now(),id).run();tags();return clamp(progress);}
export async function computeRealPercentFromChecklist(id:string){const list=await getChecklist(id),weight=list.reduce((a,i)=>a+i.weight,0);return weight?clamp(list.reduce((a,i)=>a+i.progress*i.weight,0)/weight):0;}
async function writeUpdate(serviceId:string,percent:number,description:string,payload:Record<string,unknown>,source:string){if(!await getServiceById(serviceId))throw new Error("Serviço não encontrado");const id=randomUUID(),now=Date.now();await getD1().batch([getD1().prepare("INSERT INTO service_updates(id,service_id,created_at,report_date,manual_percent,real_percent,description,mode,token_code,previous_percent,payload_json,source) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12)").bind(id,serviceId,now,payload.reportDate??null,payload.manualPercent??null,percent,description,payload.mode??null,payload.token??null,payload.previousPercent??null,JSON.stringify(payload),source),getD1().prepare("UPDATE services SET progress=?1,status=CASE WHEN ?1>=100 THEN 'concluded' ELSE status END,updated_at=?2 WHERE id=?3").bind(percent,now,serviceId)]);tags();return{id,now};}
export async function addManualUpdate(serviceId:string,input:ManualUpdateInput,_opts?:{skipRecompute?:boolean}){const percent=clamp(input.manualPercent),payload={...input,manualPercent:percent,realPercentSnapshot:percent,audit:{submittedAt:Date.now(),token:input.token,previousPercent:input.previousPercent,newPercent:percent,ip:input.ip}};const {id,now}=await writeUpdate(serviceId,percent,input.description.trim(),payload,"runtime");return{realPercent:percent,update:{...payload,id,serviceId,createdAt:now,date:input.reportDate??null,description:input.description,percent} as ServiceUpdate};}
export async function addComputedUpdate(serviceId:string,realPercent:number,note?:string,token?:string){return (await writeUpdate(serviceId,clamp(realPercent),note??"",{token,realPercentSnapshot:clamp(realPercent)},"computed")).id;}
export async function removeEvidenceFromUpdate(serviceId:string,updateId:string,url:string){const row=await getD1().prepare("SELECT payload_json FROM service_updates WHERE id=?1 AND service_id=?2").bind(updateId,serviceId).first<{payload_json:string}>();if(!row)return false;const p=JSON.parse(row.payload_json) as {evidences?:Array<{url:string}>};p.evidences=(p.evidences??[]).filter(e=>e.url!==url);await getD1().prepare("UPDATE service_updates SET payload_json=?1 WHERE id=?2").bind(JSON.stringify(p),updateId).run();return true;}
export async function listUpdates(id:string,limit=50){return (await allWithMetrics<D1Update>("updates.listRecent",getD1().prepare("SELECT id,service_id,created_at,report_date,manual_percent,real_percent,description,mode,token_code,previous_percent,payload_json,source FROM service_updates WHERE service_id=?1 ORDER BY created_at DESC,id DESC LIMIT ?2").bind(id,Math.min(limit,200)))).map(mapUpdate);}
export async function listServices(filter?:{status?:ServiceStatus;company?:string;packageId?:string}){const clauses:string[]=[],v:unknown[]=[];if(filter?.status){v.push(status(filter.status));clauses.push(`status=?${v.length}`)}if(filter?.company){v.push(filter.company);clauses.push(`company_id=?${v.length}`)}if(filter?.packageId){v.push(filter.packageId);clauses.push(`package_id=?${v.length}`)}return ((await getD1().prepare(`SELECT ${fields} FROM services ${clauses.length?`WHERE ${clauses.join(" AND ")}`:""} ORDER BY created_at DESC,id DESC`).bind(...v).all<D1Service>()).results??[]).map(mapService);}
export async function deleteService(id:string){const found=await getServiceById(id);if(!found)return false;await getD1().prepare("DELETE FROM services WHERE id=?1").bind(id).run();tags();return true;}
