import { execFileSync } from "node:child_process";
import { mkdtempSync,readFileSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll,beforeAll,beforeEach,describe,expect,it } from "vitest";
const dir=mkdtempSync(join(tmpdir(),"d1-runtime-")),db=join(dir,"db.sqlite");
const sql=(statement:string)=>execFileSync("sqlite3",[db,statement],{encoding:"utf8"}).trim();
beforeAll(()=>{execFileSync("sqlite3",[db],{input:readFileSync("migrations/0001_d1_initial.sql")});execFileSync("sqlite3",[db],{input:readFileSync("migrations/0002_d1_runtime.sql")});execFileSync("sqlite3",[db],{input:readFileSync("migrations/0003_d1_performance.sql")});});afterAll(()=>rmSync(dir,{recursive:true,force:true}));
beforeEach(()=>sql("DELETE FROM package_shares;DELETE FROM access_tokens;DELETE FROM package_folders;DELETE FROM services;DELETE FROM packages;"));
describe("D1 runtime schema",()=>{
 it("maintains service stats, package counts and conclusion/reopen/delete",()=>{sql("INSERT INTO packages(id,name,created_at,updated_at)VALUES('p','P',1,1);INSERT INTO services(id,os,status,progress,package_id,created_at,updated_at)VALUES('s','OS-42','open',0,'p',1,1)");expect(sql("SELECT total||','||open||','||concluded FROM service_stats")).toBe("1,1,0");expect(sql("SELECT services_count FROM packages")).toBe("1");sql("UPDATE services SET progress=100,updated_at=2 WHERE id='s'");expect(sql("SELECT status FROM services")).toBe("concluded");sql("UPDATE services SET progress=20,status='pending',updated_at=3 WHERE id='s'");expect(sql("SELECT pending FROM service_stats")).toBe("1");sql("DELETE FROM services WHERE id='s'");expect(sql("SELECT total FROM service_stats")).toBe("0");});
 it("synchronizes partial search fields with FTS on insert/update/delete",()=>{sql("INSERT INTO services(id,os,oc,tag,code,equipment_name,sector,company_id,company_name,cnpj,status,progress,created_at,updated_at)VALUES('fts','450012','OC77','TURB-9','COD-X9','Compressor Alfa','Caldeiraria','COMP-77','Empresa Teste','12.345.678/0001-90','open',0,4,4)");for(const q of ["0012","C77","URB","OD-X","pressor","ldeira","OMP-7","presa Tes","345.678"])expect(sql(`SELECT id FROM services_fts WHERE services_fts MATCH '\"${q}\"'`)).toBe("fts");sql("UPDATE services SET os='NEW-OS',oc='NEW-OC',tag='NEW-TAG',equipment_name='Bomba Beta',sector='Novo Setor',company_id='NEW-COMP',company_name='Nova Empresa' WHERE id='fts'");expect(sql("SELECT count(*) FROM services_fts WHERE services_fts MATCH 'Compressor'")).toBe("0");for(const q of ["NEW-OS","NEW-OC","NEW-TAG","Beta","Novo Set","NEW-COMP","Nova Empresa"])expect(sql(`SELECT id FROM services_fts WHERE services_fts MATCH '"${q}"'`)).toBe("fts");sql("DELETE FROM services WHERE id='fts'");expect(sql("SELECT count(*) FROM services_fts WHERE services_fts MATCH 'Beta'")).toBe("0");});
 it("supports folders, tokens, updates and package shares",()=>{sql("INSERT INTO packages(id,name,created_at,updated_at)VALUES('p2','P2',1,1);INSERT INTO services(id,os,status,progress,created_at,updated_at)VALUES('s2','2','open',0,1,1);UPDATE services SET package_id='p2' WHERE id='s2';INSERT INTO package_folders(id,package_id,name,service_ids_json,created_at,updated_at)VALUES('f','p2','F','[\"s2\"]',1,1);INSERT INTO access_tokens(token_code,target_type,target_id,active,status,created_at,updated_at)VALUES('TOK','folder','f',1,'active',1,1);INSERT INTO service_updates(id,service_id,created_at,payload_json,source)VALUES('u','s2',1,'{\"resources\":[]}','runtime');INSERT INTO package_shares(id,token,package_id,service_ids_json,created_at,updated_at)VALUES('sh','share','p2','[\"s2\"]',1,1)");expect(sql("SELECT service_ids_json FROM package_folders WHERE id='f'")).toBe('["s2"]');expect(sql("SELECT token_code FROM access_tokens WHERE target_type='folder' AND target_id='f' AND active=1 ORDER BY created_at DESC LIMIT 1")).toBe("TOK");expect(sql("SELECT payload_json FROM service_updates WHERE service_id='s2' ORDER BY created_at ASC,id ASC")).toBe('{"resources":[]}');expect(sql("SELECT token FROM package_shares WHERE active=1")).toBe("share");sql("DELETE FROM services WHERE id='s2'");});
 it("keeps package counters consistent across add, move, unlink and delete",()=>{sql("INSERT INTO packages(id,name,created_at,updated_at)VALUES('pa','A',1,1),('pb','B',1,1);INSERT INTO services(id,os,status,progress,created_at,updated_at)VALUES('move','M','open',0,1,1);UPDATE services SET package_id='pa' WHERE id='move'");expect(sql("SELECT services_count FROM packages WHERE id='pa'")).toBe("1");sql("UPDATE services SET package_id='pb' WHERE id='move'");expect(sql("SELECT services_count FROM packages WHERE id IN('pa','pb') ORDER BY id")).toBe("0\n1");sql("UPDATE services SET package_id=NULL WHERE id='move'");expect(sql("SELECT services_count FROM packages WHERE id='pb'")).toBe("0");sql("UPDATE services SET package_id='pa' WHERE id='move';DELETE FROM services WHERE id='move'");expect(sql("SELECT services_count FROM packages WHERE id='pa'")).toBe("0");});
 it("updates all status counters without drift",()=>{sql("INSERT INTO services(id,os,status,progress,created_at,updated_at)VALUES('stats','S','open',0,1,1)");expect(sql("SELECT open FROM service_stats")).toBe("1");sql("UPDATE services SET status='pending' WHERE id='stats'");expect(sql("SELECT open||','||pending FROM service_stats")).toBe("0,1");sql("UPDATE services SET progress=100 WHERE id='stats'");expect(sql("SELECT pending||','||concluded FROM service_stats")).toBe("0,1");sql("UPDATE services SET progress=25,status='pending' WHERE id='stats'");expect(sql("SELECT pending||','||concluded FROM service_stats")).toBe("1,0");sql("DELETE FROM services WHERE id='stats'");expect(sql("SELECT total FROM service_stats")).toBe("0");});
});
